version: 2
jobs:
  build:
    docker:
      - image: namachan10777/procml:latest

    working_directory: /ci

    steps:
      - checkout
      - run:
          name: build
          command: eval `opam config env` && jbuilder build
